### ISSUE TITLE
Multiple row reorder

### ISSUE THREAD

**Issue by paciox** [DataTables/RowReorder#31]
Where this #17  has finished in 7 years? I can't find anything and now your enormous backlog is empty

**Comment by AllanJard** [comment]
> now your enormous backlog is empty

Your kidding? Providing free support and development for a project the size of DataTables takes many hours every day? I _wish_ it were empty because the support burden is often too much for me.

As I noted in the PR, you are welcome to update the code if this feature is important for you. It isn't something that I'm currently working on.

**Comment by paciox** [comment]
> > now your enormous backlog is empty
> 
> Your kidding? Providing free support and development for a project the size of DataTables takes many hours every day? I _wish_ it were empty because the support burden is often too much for me.
> 
> As I noted in the PR, you are welcome to update the code if this feature is important for you. It isn't something that I'm currently working on.

Won't happen. What version of datatable was running at the time of the pr exactly?
Can we at least know this information?
I can't seem to find it anywhere

Thanks

**Comment by AllanJard** [comment]
Probably don't need to have this conversation in two places. Closing this one.
